### ISSUE TITLE
Compatibility issues between puppeteer and chrome

### ISSUE THREAD

**Issue by remyoucef** [apifytech/apify-actor-docker#10]
The docker images that has chrome installed with the latest stable version (e.g. 78.**) is not compatible with certain puppeteer versions (e.g. 1.8.1).

**Comment by jancurn** [comment]
We always try to have there the latest version of Chrome and stay with the latest Puppeteer. It's not really possible to have Chrome that will work with every legacy version of Puppeteer

**Comment by remyoucef** [comment]
You can't force the user to use the latest version when a certain version work for him. This will create an unpredictable results and the user will have to change the actor code to fit with the new versions.

**Comment by jancurn** [comment]
I see. Perhaps we could add more tags to Docker images, saying which Chrome or Puppeteer version is included. The user would have to specify that tag in his Dockerfile in the `BUILD` instruction. Would that work?

**Comment by remyoucef** [comment]
Yes this works, using tags for Puppeteer is enough. By the way, I'm working
on customer project which needs to be able to use specific versions of
Puppeteer and Chrome, maybe I can contribute once I'm done. What do you
think?

**Comment by jancurn** [comment]
Yeah that would be great!

**Comment by remyoucef** [comment]
Ok, happy to work on it.
